### ISSUE TITLE
Cant run from VSC.

### ISSUE THREAD

**Issue by kcvinker** [Araq/nimedit#10]
Hi,
I tried to run nimedit.nim from VSC. This is the compiler message ;
"buffer.nim(444, 23) Error: usage of 'isNil' is a user-defined error"
What to do ?

**Comment by Araq** [comment]
I merged a pull request so that the codebase compiles with 0.19.

**Comment by kcvinker** [comment]
I am completely ignorant about this "pull request" stuff. So This is my humble question. What do i need to do in order to run nimedit ? Waiting for next release ?

**Comment by Araq** [comment]
No, you need to try again. :-)
