### ISSUE TITLE
comparison nimedit vs aporia

### ISSUE THREAD

**Issue by timotheecour** [Araq/nimedit#12]
* I couldn't find any mention of aporia in this repo nor in issues; seems to me nimedit is the successor to aporia and aporia is not developped anymore but nimedit is; is that correct?
* what are feature differences wrt aporia?

**Comment by Araq** [comment]
Neither is welldeveloped but the primary difference is that Aporia is based on GTK2, Nimedit on SDL2. Nimedit started as an experiment on "immediate mode" UIs, Aporia started as "IDE for Nim". :-)

I hope(d) that the implementation based on SDL2 would allow us to run it in the browser via emscripten and allow for easy embedding of the editor into game engines and the like.

Oh and I also hoped it would encourage contributions as SDL2 is easier to work with than Gtk2, especially on OSX and Windows.

**Comment by juancarlospaco** [comment]
I was wondering what happened with the NimX branch?, why it born?, why it died?, any postmortem.

**Comment by Araq** [comment]
In the NimX branch we tried to make the font rendering use ``nimx``'s font rendering which is based on OpenGL, but we never got it to work. Apparently the way Nimedit deals with pixel coordinates doesn't work with Retina displays.
