### ISSUE TITLE
Download for NimEdit Windows Binary goes to Nim-Lang.org

### ISSUE THREAD

**Issue by Pebaz** [Araq/nimedit#14]
This [page](https://nim-lang.org/nimedit/) contains a download link to the Nim-Lang.org main website.

I am trying to run NimEdit on Windows.

I have tried building from source on Windows but there is an error with loading the SDL2_TTF DLL.

If I could just download a precompiled binary that would be great!

**Comment by ekie** [comment]
http://nim-lang.org/nimedit/download/NimEdit_0.94.exe

**Comment by Pebaz** [comment]
Thank you!  Unfortunately, I installed it just fine but when you double click the executable, it does nothing. When you launch it from a terminal, it exits immediately and opens no windows or prints to any output stream.

**Comment by ZenTalonsZ** [comment]
Same here

**Comment by aronfeher** [comment]
The problem still persists.

**Comment by Araq** [comment]
Thanks. Fixed.
