### ISSUE TITLE
Scrollbar needs improvement

### ISSUE THREAD

**Issue by lilkeet** [Araq/nimedit#22]
- The scrollbar thinks that the page height is the amount of lines in the file, so it hits the bottom of its range of motion before you're done scrolling. This is very noticeable on smaller files.
- At least on my machine (ubuntu running kde plasma), the scrollbar doesnt move when clicked and dragged. The e var Event that gets passed to it has an invalid kind enum (32512). Some digging into it reveals that this bug Event is getting input quite often, happening many times a second. The best i could find online about it was [this](https://stackoverflow.com/questions/18454588/sdl2-not-receiving-window-events) but that would mean that there's any issue w/ the nim sdl2 library.
- Still need to add a gradient.

I was planning on working on this for a bit. ill be updating my fork as i go.

**Comment by lilkeet** [comment]
@Araq could you clarify what you want the scrollbar to look like? I'd be happy to try to implement it, or you could change the draw proc in the scrollbar file to your liking.

**Comment by Araq** [comment]
The screenshot shows it how I've always seen it: https://camo.githubusercontent.com/b3d3cec8828a7378dae979b163ad190ca040c09e71fccbf3e0c204410350f6f7/68747470733a2f2f6269746275636b65742e6f72672f7265706f2f65653564614b2f696d616765732f3637353531383830342d73686f74312e706e67

And it's fine this way, assuming it would work properly.

**Comment by lilkeet** [comment]
Then this issue is fixed in my fork. I still have lots of changes i need to make to other things tho so ill make a pr when I'm done.
